# Generated by Django 2.2.5 on 2019-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='end_date',
            field=models.DateTimeField(verbose_name='End created'),
        ),
    ]
